CREATE TABLE IF NOT EXISTS carts (
    id SERIAL PRIMARY KEY,
    product_id VARCHAR NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    count INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_carts_product_id ON carts(product_id);


ALTER TABLE carts
ADD COLUMN tgid BIGINT; 

