CREATE TABLE IF NOT EXISTS carts (
    id SERIAL PRIMARY KEY,
    product_id VARCHAR NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    count INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_carts_product_id ON carts(product_id);

ALTER TABLE product ADD COLUMN IF NOT EXISTS "index" INTEGER;
ALTER TABLE product ADD COLUMN IF NOT EXISTS post_id VARCHAR DEFAULT '';
ALTER TABLE product ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE product ADD COLUMN IF NOT EXISTS is_new BOOLEAN DEFAULT FALSE;
ALTER TABLE product ADD COLUMN IF NOT EXISTS discount_price INTEGER DEFAULT 0;
ALTER TABLE carts
ADD COLUMN tgid BIGINT; 

