CREATE TABLE IF NOT EXISTS iiko_tokens(
    id SERIAL PRIMARY KEY,
    token TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE category
    ALTER COLUMN id TYPE VARCHAR
    USING id::varchar;

ALTER TABLE category
    ADD COLUMN IF NOT EXISTS parent_id VARCHAR DEFAULT '';

ALTER TABLE category
    ADD COLUMN IF NOT EXISTS is_included_in_menu BOOLEAN DEFAULT FALSE;

ALTER TABLE category
    ADD COLUMN IF NOT EXISTS is_group_modifier BOOLEAN DEFAULT FALSE;

ALTER TABLE category
    ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE category
    ADD COLUMN IF NOT EXISTS index INT DEFAULT 0;

ALTER TABLE category
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT FALSE;