ALTER TABLE invoices
  ADD COLUMN IF NOT EXISTS click_paydoc_id BIGINT,
  ADD COLUMN IF NOT EXISTS merchant_prepare_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS invoices_merchant_prepare_id_uq
  ON invoices(merchant_prepare_id);

CREATE UNIQUE INDEX IF NOT EXISTS invoices_merchant_trans_id_uq
  ON invoices(merchant_trans_id);

ALTER TABLE clients
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;